[package]
name = "wp-schema"
version = "0.1.3"
edition = "2024"

[lib]
name = "wp_schema"

[dependencies]
orion-error = "0.5.5"
orion_conf =  { version = "~0.3", features = ["yaml","toml"]}
#wp_parser = { package = "wp-parser",git = "https://cnb.cool/dy-sec/core-engine/data-parse/wp-engine.git", branch = "develop"  }
#wp_lang = { package = "wp-lang", git = "https://cnb.cool/dy-sec/core-engine/data-parse/wp-engine.git", branch = "develop" }
wp-log=    { package = "wp-log", git = "https://cnb.cool/dy-sec/core-engine/data-parse/wp-infras",tag = "v0.2.1" }
wp-error = { package = "wp-error", git = "https://cnb.cool/dy-sec/core-engine/data-parse/wp-infras",tag = "v0.2.1" }
# 引入 schema 定义，兼容新版引擎的 proto/text 相关格式
# Core dependencies
anyhow = "~1.0"
chrono = "~0.4"
#clap = { version = "~4.0", features = ["derive"] }
log = "~0.4"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
winnow = "~0.7"
educe = { version = "~0.4", default-features = false, features = ["Default", "Debug"] }

actix-web = { version = "~4.4", optional = true }
prometheus = { version = "~0.13", optional = true }
regex = { version = "~1.10", optional = true }
lazy_static = { version = "~1.5", optional = true }
uuid = { version = "1.11", features = ["v4"], optional = true }



[dev-dependencies]
env_logger = "~0.10"
chrono = "~0.4"
